apiVersion: integration/v1
kind: Step
name: message-send
tags:
  - collaboration
  - messaging
  - alerts
  - alerting
version: 1
summary: Send a message to a Slack channel
description: |
  Sends a message to a Slack channel that you choose.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/slack-step-message-send
schemas:
  spec:
    source: file
    file: spec.schema.json
examples:
  - summary: Send a message
    content:
      apiVersion: v1
      kind: Step
      name: send-message
      image: relaysh/slack-step-message-send
      spec:
        channel: !Parameter slack-channel
        connection: !Connection { type: slack, name: my-slack-account }
        message: !Parameter message # Example: "hello Relay!"
        blocks: !Parameter blocks # Example: "[{"type": "section","text": {"type": "mrkdwn", "text": "Hello from Relay!"}}]"
        username: !Parameter username # Example: "Relay Workflows"
