apiVersion: integration/v1
kind: Step
name: message-send
tags:
  - collaboration
  - messaging
  - alerts
  - alerting
version: 1
summary: Send a message to a Slack channel
description: |
  Sends a message to a Slack channel that you choose.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/slack-step-message-send
schemas:
  spec:
    source: file
    file: spec.schema.json
examples:
  - summary: Send a Slack message using text
    content:
      apiVersion: v1
      kind: Step
      name: send-message
      image: relaysh/slack-step-message-send
      spec:
        channel: ${parameters.slack-channel}
        connection: ${connections.slack.my-slack-account}
        message: ${parameters.message} # Example: "hello Relay!"
        username: ${parameters.username} # Example: "Relay Workflows"
  - summary: Send a Slack message using blocks
    content:
      apiVersion: v1
      kind: Step
      name: send-message
      image: relaysh/slack-step-message-send
      spec:
        channel: ${parameters.slack-channel}
        connection: ${connections.slack.my-slack-account}
        blocks: ${parameters.block} # Example: '[{"type": "section","text": {"type": "mrkdwn", "text": "Hello from Relay!"}}]'
        username: ${parameters.username} # Example: "Relay Workflows"
